namespace BeatTogether.DedicatedServer.Messaging.Enums
{
    public enum MenuRpcPacketType : byte
    {
        SetPlayersMissingEntitlementsToLevel = 0,
        GetIsEntitledToLevel = 1,
        SetIsEntitledToLevel = 2,
        InvalidateLevelEntitlementStatuses = 3,
        SelectLevelPack = 4,
        SetSelectedBeatmap = 5,
        GetSelectedBeatmap = 6,
        RecommendBeatmap = 7,
        ClearRecommendedBeatmap = 8,
        GetRecommendedBeatmap = 9,
        SetSelectedGameplayModifiers = 10,
        GetSelectedGameplayModifiers = 11,
        RecommendGameplayModifiers = 12,
        ClearRecommendedGameplayModifiers = 13,
        GetRecommendedGameplayModifiers = 14,
        LevelLoadError = 15,
        LevelLoadSuccess = 16,
        StartLevel = 17,
        GetStartedLevel = 18,
        CancelLevelStart = 19,
        GetMultiplayerGameState = 20,
        SetMultiplayerGameState = 21,
        GetIsReady = 22,
        SetIsReady = 23,
        SetStartGameTime = 24,
        CancelStartGameTime = 25,
        GetIsInLobby = 26,
        SetIsInLobby = 27,
        GetCountdownEndTime = 28,
        SetCountdownEndTime = 29,
        CancelCountdown = 30,
        GetOwnedSongPacks = 31,
        SetOwnedSongPacks = 32,
        RequestKickPlayer = 33,
        GetPermissionConfiguration = 34,
        SetPermissionConfiguration = 35,
        GetIsStartButtonEnabled = 36,
        SetIsStartButtonEnabled = 37,
        ClearSelectedBeatmap = 38,
        ClearSelectedGameplayModifiers = 39
    }
}
